### ISSUE TITLE
Some terms are not unified

### ISSUE THREAD

**Issue by k-tamura** [openstandia/keycloak-documentation-i18n#441]
There are some terms should be unified.

For example (in Japanese),

* 「ー」を付けるかどうか

   - スタンドアローン
   - ディレクトリー
   - リポジトリー
   - ユーティリティー
   - プロパティー
   - ボディー
   - セキュリティー
   - ストアー
   - コンテナー
   - クエリー
   - レジストリー
   - ベアラー
   - バイナリー
   - エントリー
   - クラスター
   - マシン
  　
→ルールの通り、省略禁止。カタカナで発音したときに伸ばしているなら、付ける（基本的に付ける）。

*  「・」を付けるかどうか
   - インストール・ページ
   - カット・アンド・ペースト
   - キーストア・ファイル
   - クイック・スタート
   - クリック・ジャッキング
   - クレデンシャル・タイプ
   - コメント・アウト
   - サーバー・ログ
   - システム・プロパティ
   - シングル・サインオン
   - ステータス・コード
   - データベース・スキーマ
   - データベース・タイプ
   - データベース・ベンダー
   - トラスト・ストア
   - バインド・アドレス
   - ベスト・プラクティス
   - ブルート・フォース
   - マイクロ・リリース
   - マイナー・チェンジ
   - マイナー・リリース
   - リソース・サーバー
   - ユーザー・ストア
   - ユーザー・パスワード
   - リバース・プロキシ
   - リモート・サーバー
   - ループバック・アドレス 
   - ログイン・ダイアログ
  　
「Single sign-on」：「シングル・サインオン」のように、半角スペースがあれば「・」を入れる、と言う単純なルールで統一した方が楽だと思うが。全て翻訳が終わってから「・」がうるさい単語は「・」を削るとか。

 ※これらのチェックはwordのスペルチェック機能で検証するのが手っ取り早いかも
  　

* 漢字にするかどうか
   - たとえば
   - おすすめ
   - ください
   - とおり
   - すでに
   - さまざまな
   - あと
   - はじめる
   - いま
   - つぎ
   - できる
   - したがって
   - もの

  　

* コメントを日本語化すべきか
  　
  ソースコード内のコメントを日本語化すべきか
  　

* どの記法に統一するか
   - 「（）」かっこを全角にするかどうか
   - 「:」、次の通りの意味の
   - 全角英数字を使用するかどうか
  　

* 英語のままにするかどうか
   - OPTIONAL/REQUIRED
   - 画面項目を日本語で書くかどうか(画面キャプチャが英語なので)
  　

* どの呼び方に統一するか
   - 管理コンソール/Admin Console
   - プロファイル/プロフィール
   - バックチャンネル/バックチャネル
   - マイグレーション/移行
   - 委任/委譲
   - 要求/リクエスト
   - 応答/レスポンス
   - プロダクション環境/本番環境
   - User Infoエンドポイント/ユーザー情報エンドポイント
   - インプリシット・フロー/暗黙フロー
   - Resource Owner Password Credentials Grant Type
   - デフォルト/規定値
   - ガーベージ、ガーベッジ、ガベージ
   - リストページ/一覧ページ
   - コネクションプール/接続プール
   - インターフェイス/インターフェース
   - マスター・レルム(Master?)
   - 接続プール/コネクションプール
   - ユーザー・ストレージ・フェデレーション/ユーザー・ストレージ連携
  　

* 謙譲語・尊敬語の使用

    ガイド（しかも自社製品ではない）なので、謙譲語・尊敬語は不要
  　

* 訳し方
   - secure(セキュアにする/セキュリティ保護する/保護する)
   - ship
   - Installation
   - permission
   - deployment
   - chapter
   - section
   - configuration(Google翻訳では必ずと言っていいほど「構成」と訳すが、自分は殆どの場合で「設定」と訳している)
   - optional：任意/省略可/オプション
   - subscribe
   - Forgot Password
   - Remember Me
   - no longer 
   - target client
   - promise(クラス名っぽい使われ方をしていたような)
   - type (「タイプ」、「種類」、「型」)
   - one or more「1つ以上」に統一したい
   - distribution：配布物？
   - strategy：「戦略」って大げさな気が...「decision strategy」とか。
   - federated
   - classic ：「古典的な」、「クラシックな」
   - given 
   - you：「あなた」と言う訳し方は日本語のガイドでは違和感を感じるので
   - we：youと同様
   - Composite Role
   - relay state（SAMLのRelayStateのこと）
   - policy aggregation：「ポリシー集約」？
   - Representation
   - iterate
   - vs
   - store：保存する（DBなどに対して永続化する場合）と格納する（一時変数などに値を保持する）を使い分けた方がよさそう（Google翻訳された「格納する」をよく見かけるが）
   - security attack vector
   - impersonization / impersonate 
   - Json Web Token
   - introspect 
   - inbound
   - outgoing
   - contract 
   - Execution
   - federate：「連携する」？ 
   - packaging：「パッケージング」or「パッケージ化」
   - clickjacking

**Comment by pro-amano** [comment]
\\192.174.105.81\OpenStandia\share\docs\00_プロジェクト・維持管理関連\2017\201710-JIC-IAM調査\10.営業活動\07.情報発信サイト整備(社外)\Keycloakドキュメント翻訳\jtf_style_guide.pdf  より、

> * 漢字にするかどうか 

「ひらがなと漢字の両方の表記が一般的」の表中の言葉も対象です。

> 「（）」かっこを全角にするかどうか  

ガイドでは全角での表記なので、全角に合わせたほうがよいと思います。

**Comment by pro-amano** [comment]
* 訳し方
Requesting Party Token
Resource Owner Password Credentials Grant Type
grant type

カタカナで訳したほうがいいのか。そのままで使用するのか。

**Comment by wadahiro** [comment]
@k-tamura 

>「ー」を付けるかどうか

[外来語（カタカナ）表記ガイドライン第3版](https://www.jtca.org/standardization/katakana_guide_3_20171222.pdf) でかなり細かく規定されているので、これに従いましょう。基本「ー」をつけるのですが、 **英語の語尾の‐re にあたるものは、原則として長音符号「ー」を付けない。** というルールがあるので、**ストアー** は **ストア** になります。

> 「・」を付けるかどうか

[JTF日本語標準スタイルガイド](https://www.jtf.jp/jp/style_guide/pdf/jtf_style_guide.pdf)より引用ですが、

>語の区切りを入れる方が望ましいが、区切りを多用しない。原語がハイフンでつながれている場
合、それぞれの語の独立性が希薄で判読に困難がない場合、語句が短い場合には区切りを入れな
い方が望ましい。
・ 区切りを入れないカタカナ複合語の例
ログイン、チェックアウト、リアルタイム、ダブルクリック、スタイルガイド、スピードア
ップ、バーコード

とあります。

* 〜8文字の場合は「・」を付けない
* 9文字〜の場合は「・」を付ける

ぐらいでどうでしょう？ Issue説明に書かれていた例だと以下のようになります。

```
インストール・ページ
カット・アンド・ペースト
キーストア・ファイル
クイックスタート
クリック・ジャッキング
クレデンシャル・タイプ
コメントアウト
サーバーログ
システム・プロパティ
シングル・サインオン
ステータスコード
データベース・スキーマ
データベース・タイプ
データベース・ベンダー
トラストストア
バインドアドレス
ベスト・プラクティス
ブルートフォース
マイクロリリース
マイナーチェンジ
マイナーリリース
リソースサーバー
ユーザーストア
ユーザー・パスワード
リバース・プロキシー
リモートサーバー
ループバック・アドレス
ログイン・ダイアログ
```

**Comment by k-tamura** [comment]
>   〜8文字の場合は「・」を付けない
>   9文字〜の場合は「・」を付ける

文字数を判断基準にすると「サーバーサイドとクライアント・サイド」のような若干気持ち悪い訳になることがあります。あと、8文字と9文字のカウントを毎回しないといけないので、ちょっと面倒ですかね。

**Comment by wadahiro** [comment]
@k-tamura 

> 漢字にするかどうか

[JTF日本語標準スタイルガイド](https://www.jtf.jp/jp/style_guide/pdf/jtf_style_guide.pdf)にあるものは従います。ないものでも、このガイド文章内で出てくるものはそれに従う（このガイドも同じガイドで書かれていると思われるため）。Issue説明にある例だと以下のようになります。
「今」だけなかったのですが、主観で漢字にしましたが、翻訳で「今」って使うところありますかね？ 直訳すぎる可能性があるので訳文を見直すほうがいいかも。

```
たとえば
お勧め
ください
とおり
すでに
さまざまな
後
始める
今
次
できる
したがって
もの
```

**Comment by wadahiro** [comment]
@k-tamura 

> 文字数を判断基準にすると「サーバーサイドとクライアント・サイド」のような若干気持ち悪い訳になることがあります。

では、

* 〜8文字の場合は「・」を付けない
* 9文字〜の場合は「・」を付ける
* 上記で違和感があるものは個別相談 (例：クライアント・サイド → クライアントサイド にする)

で。

> あと、8文字と9文字のカウントを毎回しないといけないので、ちょっと面倒ですかね。

これは初見の人だけが訳語登録しちゃえば、後はクリックして使うだけなので特に問題ないかと。

**Comment by k-tamura** [comment]
どこかで「いま」という訳を見ましたが、まあ、あまりガイドで出てくる単語じゃないですね。意訳したかもしれません。

**Comment by wadahiro** [comment]
>どの記法に統一するか
>
>「（）」かっこを全角にするかどうか

* [JTF日本語標準スタイルガイド](https://www.jtf.jp/jp/style_guide/pdf/jtf_style_guide.pdf)に従い、基本全角
* ただし、英語フレーズの中で出てきて全角にするとアンバランスになるものは半角のままとする（例： HTTP（S）→HTTP(S) ）

>「:」、次の通りの意味の

* [JTF日本語標準スタイルガイド](https://www.jtf.jp/jp/style_guide/pdf/jtf_style_guide.pdf)に従い、訳文では使わない。英語だと、「以下/次に示す」という意味があるので、翻訳で言いかえる。
* ただし、「日時：3 月 16 日午後 1 時、例：～」のように見出し語とその説明の間には使ってOK。その場合は全角コロンとする。

>全角英数字を使用するかどうか

* [JTF日本語標準スタイルガイド](https://www.jtf.jp/jp/style_guide/pdf/jtf_style_guide.pdf)に従い、数字とアルファベットは半角で表記する

**Comment by wadahiro** [comment]
@k-tamura 

> 「サーバーサイドとクライアント・サイド」

これ原文みたら、これらは server-side、client-side となっていたので、原語がハイフンでつながれている場合なので「・」なしでした。訳語登録しておきます。

**Comment by wadahiro** [comment]
上記方針に従い下記のように用語集を変更しておいたのでメモ。

### 長音
* スタンドアロン → スタンドアローン
* ディレクトリ → ディレクトリー
* プロパティー 追加
* セキュリティ → セキュリティー
* ボディー 追加
* コンテナー 追加
* クエリー 追加
* レジストリー 追加
* バイナリー 追加
* エントリー 追加

### 中点
* バインド・アドレス → バインドアドレス
* サーバーログ 追加
* ステータスコード 追加
* ブルートフォース 追加
* マイクロリリース 追加
* マイナーチェンジ 追加
* マイナーリリース 追加
* ユーザーストア 追加
* リモートサーバー 追加
* クライアントサイド 追加
* サーバーサイド 追加

**Comment by k-tamura** [comment]
@wadahiro このissue、一応対策したのでクローズしておきますか？

**Comment by k-tamura** [comment]
クローズします
